tor -f <torrc>
curl --socks5-hostname 127.0.0.1:9050 https://check.torproject.org

## torrc

# This file was generated by Tor; if you edit it, comments will noqt be preserved
# The old torrc file was renamed to torrc.orig.1 or similar, and Tor will ignore it

# ExitNodes {ru}
# StrictNodes 1
